// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trendyol.Data.TrendyolContext;

namespace Trendyol.Data.Migrations
{
    [DbContext(typeof(TrendyolPostgreSqlContext))]
    partial class TrendyolPostgreSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Trendyol.Data.Models.DeepLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DeepLinkRequest")
                        .HasColumnType("text");

                    b.Property<string>("DeepLinkResponse")
                        .HasColumnType("text");

                    b.Property<string>("WebUrlRequest")
                        .HasColumnType("text");

                    b.Property<string>("WebUrlResponse")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeepLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
