CREATE TABLE "DeepLinks" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DeepLinkRequest" text NULL,
    "WebUrlRequest" text NULL,
    "WebUrlResponse" text NULL,
    "DeepLinkResponse" text NULL
)